title: Jonathan McDill
description: Writing by Jonathan McDill.
url: "https://jonathanmcdill.com"
permalink: /blog/:title/
timezone: America/New_York
counterdev: ee94ae83-2d5d-4a07-88e6-8c3e8a740713
exclude:
  - component-lab
  - node_modules
  - package.json
  - package-lock.json

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
